/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rn_a2;

import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Domani
 */
public class ChatGUI extends javax.swing.JFrame {

    /**
     * Creates new form ChatGUI
     */
    private Client client;

    public ChatGUI() {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        initComponents();
    }
    private void startFetchThread()
    {
        //Thread A -> UserList empfangen
        new Thread(new Runnable() {
            @Override
            public void run() {
                //prüft die event queue auf den aktuellen Thread.isInterrupted()
                while (!Thread.interrupted()) {
                    if (client != null) {
                        try {
                            
                            client.updateUserlist();
                        } catch (IOException ex) {
                            Logger.getLogger(RN_A2.class.getName()).log(Level.SEVERE, null, ex);
                        }
                      
                        updateUsers(client.getUsers());
                    }
                    try {
                        Thread.sleep(5000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(RN_A2.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }
        }).start();
    }
    
    public void setClient(Client pClient) throws IOException {
        this.client = pClient;
        client.setCallback(new ICallback() {
            @Override
            public void call(final String message) {
                java.awt.EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        appendUserMessage(message);
                    }
                });
            }
        });
        startFetchThread();
    }
    
    public Client getClient()
    {
        return this.client;
    }

    private void appendUserMessage(String message) {
        jta_chatverlauf.append(message + '\n');
    }

    public void updateUsers(List<String> users) {
        DefaultListModel<String> model = (DefaultListModel<String>) jl_userlist.getModel();
        model.clear();
        for (String elem : users) {
            model.addElement(elem);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        js_scrollpane = new javax.swing.JScrollPane();
        jta_chatverlauf = new javax.swing.JTextArea();
        jtf_newmessage = new javax.swing.JTextField();
        jb_sendmessage = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_userlist = new javax.swing.JList();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jta_chatverlauf.setEditable(false);
        jta_chatverlauf.setColumns(20);
        jta_chatverlauf.setRows(5);
        js_scrollpane.setViewportView(jta_chatverlauf);

        jb_sendmessage.setText("send");
        jb_sendmessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_sendmessageActionPerformed(evt);
            }
        });

        jl_userlist.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_userlist);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(js_scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtf_newmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_sendmessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(js_scrollpane))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_newmessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_sendmessage))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_sendmessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_sendmessageActionPerformed
      client.writeToOther(jtf_newmessage.getText());
      jtf_newmessage.setText("");
    }//GEN-LAST:event_jb_sendmessageActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_sendmessage;
    private javax.swing.JList jl_userlist;
    private javax.swing.JScrollPane js_scrollpane;
    private javax.swing.JTextArea jta_chatverlauf;
    private javax.swing.JTextField jtf_newmessage;
    // End of variables declaration//GEN-END:variables
}
